import React, { createContext, useContext, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import './styles.css'
import './auth.css'

const API = '/api'
const SessionContext = createContext(null)
const stages = ['Preparación', 'Ejecución', 'Control de calidad']

async function request(path, options = {}, token) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'No se pudo completar la operación.')
  return data
}
function useSession() { return useContext(SessionContext) }
function App() {
  const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('atelier_session')) } catch { return null } })
  const start = data => { localStorage.setItem('atelier_session', JSON.stringify(data)); setSession(data) }
  const close = () => { localStorage.removeItem('atelier_session'); setSession(null) }
  return <SessionContext.Provider value={{ session, start, close }}><BrowserRouter><Routes>
    <Route path="/iniciar-sesion" element={<Public><Login /></Public>} />
    <Route path="/registro" element={<Public><Register /></Public>} />
    <Route path="/admin" element={<Protected role="admin"><Admin /></Protected>} />
    <Route path="/mis-tareas" element={<Protected role="empleado"><MyTasks /></Protected>} />
    <Route path="*" element={<Landing />} />
  </Routes></BrowserRouter></SessionContext.Provider>
}
function Landing() { const { session } = useSession(); return <Navigate to={session ? session.usuario.rol === 'admin' ? '/admin' : '/mis-tareas' : '/iniciar-sesion'} replace /> }
function Public({ children }) { const { session } = useSession(); return session ? <Landing /> : children }
function Protected({ role, children }) { const { session } = useSession(); if (!session) return <Navigate to="/iniciar-sesion" replace />; return session.usuario.rol === role ? children : <Landing /> }
function AuthPage({ title, description, children, foot }) { return <main className="auth-page"><section className="auth-card"><div className="auth-brand">El Atelier <span>HUB DE PRODUCCIÓN</span></div><p className="eyebrow">Acceso al sistema</p><h1>{title}</h1><p className="muted">{description}</p>{children}{foot && <p className="auth-foot">{foot}</p>}</section></main> }
function Login() {
  const { start } = useSession(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('/auth/iniciar-sesion', { method: 'POST', body: JSON.stringify({ email, contrasena: password }) }); start(data); navigate(data.usuario.rol === 'admin' ? '/admin' : '/mis-tareas', { replace: true }) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <AuthPage title="Bienvenido" description="Ingresá con tu cuenta para acceder a tus tareas."><form className="auth-form" onSubmit={submit}><label>Correo electrónico<input required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Contraseña<input required type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Ingresando...' : 'Iniciar sesión'}</button></form><p className="auth-foot">¿No tenés cuenta? <NavLink to="/registro">Registrate</NavLink></p></AuthPage>
}
function Register() {
  const navigate = useNavigate(); const [form, setForm] = useState({ nombre: '', email: '', password: '' }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const change = key => e => setForm({ ...form, [key]: e.target.value })
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('/auth/registro', { method: 'POST', body: JSON.stringify({ nombre: form.nombre, email: form.email, contrasena: form.password }) }); setNotice(`${data.mensaje} Ya podés iniciar sesión.`); setTimeout(() => navigate('/iniciar-sesion'), 1300) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <AuthPage title="Crear cuenta" description="Toda cuenta nueva se registra con el rol de empleado."><form className="auth-form" onSubmit={submit}><label>Nombre completo<input required value={form.nombre} onChange={change('nombre')} /></label><label>Correo electrónico<input required type="email" value={form.email} onChange={change('email')} /></label><label>Contraseña<input required minLength="8" type="password" value={form.password} onChange={change('password')} /><small>Mínimo 8 caracteres.</small></label>{error && <p className="form-error">{error}</p>}{notice && <p className="form-success">{notice}</p>}<button className="primary full" disabled={busy}>{busy ? 'Creando...' : 'Crear cuenta'}</button></form><p className="auth-foot">¿Ya tenés una cuenta? <NavLink to="/iniciar-sesion">Iniciá sesión</NavLink></p></AuthPage>
}
function Shell({ title, children }) { const { session, close } = useSession(); return <div className="app-shell auth-shell"><aside className="sidebar"><div className="brand">El Atelier<span>HUB DE PRODUCCIÓN</span></div><nav>{session.usuario.rol === 'admin' ? <NavLink to="/admin">▦ &nbsp; Administración</NavLink> : <NavLink to="/mis-tareas">▦ &nbsp; Mis tareas</NavLink>}</nav><div className="side-bottom"><div className="user"><span>{session.usuario.nombre.slice(0,2).toUpperCase()}</span><div><b>{session.usuario.nombre}</b><small>{session.usuario.rol}</small></div></div><button onClick={close}>↪ Cerrar sesión</button></div></aside><main><header><div className="crumb">{title}</div><span className="role-badge">{session.usuario.rol}</span></header><div className="content auth-content">{children}</div></main></div> }
function useData(path) { const { session, close } = useSession(); const [data, setData] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = async () => { setLoading(true); try { setData(await request(path, {}, session.token)); setError('') } catch (err) { setError(err.message); if (err.message.includes('Sesión')) close() } finally { setLoading(false) } }; useEffect(() => { load() }, [path]); return { data, loading, error, load, token: session.token } }
function Admin() {
  const users = useData('/usuarios'); const tasks = useData('/tareas'); const { token } = useSession(); const [message, setMessage] = useState('')
  const changeRole = async (id, rol) => { try { await request(`/usuarios/${id}/rol`, { method: 'PATCH', body: JSON.stringify({ rol }) }, token); users.load(); setMessage('Rol actualizado.') } catch (err) { setMessage(err.message) } }
  return <Shell title="Administración"><section className="page-heading"><div><p className="eyebrow">Administrador</p><h1>Gestión de tareas</h1><p className="muted">Creá tareas, asignalas y administrá los roles del sistema.</p></div></section>{message && <p className="notice">{message}</p>}<section className="admin-layout"><TaskForm employees={users.data.filter(u => u.rol === 'empleado' && u.activo)} token={token} onCreated={() => { tasks.load(); setMessage('Tarea creada y asignada.') }} /><section className="list-panel"><div className="section-heading"><div><h2>Todas las tareas</h2><p>{tasks.data.length} registradas</p></div></div><TaskList tasks={tasks.data} /></section></section><section className="list-panel users-panel"><div className="section-heading"><div><h2>Usuarios</h2><p>Solo el administrador puede cambiar roles.</p></div></div>{users.loading ? <p>Cargando usuarios...</p> : users.error ? <p className="form-error">{users.error}</p> : <div className="users-table">{users.data.map(user => <div key={user.id}><span><b>{user.nombre}</b><small>{user.email}</small></span><select value={user.rol} onChange={e => changeRole(user.id, e.target.value)}><option value="empleado">empleado</option><option value="admin">admin</option></select></div>)}</div>}</section></Shell>
}
function TaskForm({ employees, token, onCreated }) { const [form, setForm] = useState({ titulo: '', descripcion: '', asignado_a: '', tiempos: [30, 120, 20] }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const change = key => e => setForm({ ...form, [key]: e.target.value }); const changeTime = i => e => setForm({ ...form, tiempos: form.tiempos.map((v, index) => index === i ? e.target.value : v) })
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { await request('/tareas', { method: 'POST', body: JSON.stringify(form) }, token); setForm({ titulo: '', descripcion: '', asignado_a: '', tiempos: [30, 120, 20] }); onCreated() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <section className="task-form list-panel"><p className="eyebrow">Nueva tarea</p><h2>Crear y asignar</h2>{employees.length ? <form onSubmit={submit}><label>Título<input required value={form.titulo} onChange={change('titulo')} placeholder="Ej. Reparar portón" /></label><label>Descripción<textarea value={form.descripcion} onChange={change('descripcion')} /></label><label>Empleado<select required value={form.asignado_a} onChange={change('asignado_a')}><option value="">Seleccionar empleado</option>{employees.map(e => <option value={e.id} key={e.id}>{e.nombre}</option>)}</select></label><div className="fixed-stages"><b>Etapas fijas y tiempo estimado</b>{stages.map((stage, i) => <label key={stage}>{stage}<span><input required min="1" type="number" value={form.tiempos[i]} onChange={changeTime(i)} /> min</span></label>)}</div>{error && <p className="form-error">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Creando...' : 'Crear tarea'}</button></form> : <p className="notice">No hay empleados activos. Registrá una cuenta y asignale el rol empleado.</p>}</section> }
function TaskList({ tasks, employee, onStage, onStatus }) { if (!tasks.length) return <div className="empty compact"><h3>{employee ? 'No tenés tareas asignadas' : 'No hay tareas creadas'}</h3><p>{employee ? 'Cuando un administrador te asigne una, aparecerá aquí.' : 'Creá una tarea para comenzar.'}</p></div>; return <div className="task-list">{tasks.map(task => <TaskCard key={task.id} task={task} employee={employee} onStage={onStage} onStatus={onStatus} />)}</div> }
function TaskCard({ task, employee, onStage, onStatus }) { const done = task.etapas.filter(e => e.realizada).length; return <article className="task-card"><div className="task-card-head"><div><span className={`task-status ${task.estado.toLowerCase()}`}>{task.estado.replace('_', ' ')}</span><h3>{task.titulo}</h3><p>{task.descripcion || 'Sin descripción.'}</p></div>{!employee && <span className="assigned">{task.asignado?.nombre}</span>}</div><Progress value={task.etapas.length ? done / task.etapas.length * 100 : 0} /><p className="stage-count">{done}/{task.etapas.length} etapas completadas</p><div className="stage-list">{task.etapas.map(stage => <label key={stage.id} className={stage.realizada ? 'completed' : ''}><input disabled={!employee} type="checkbox" checked={stage.realizada} onChange={e => onStage(task.id, stage.id, e.target.checked)} /><span>{stage.nombre}<small>Tiempo estimado: {stage.minutos_estimados} min</small></span>{stage.realizada && <b>✓</b>}</label>)}</div>{employee && <label className="status-control">Estado<select value={task.estado} onChange={e => onStatus(task.id, e.target.value)}><option value="PENDIENTE">Pendiente</option><option value="EN_PROGRESO">En progreso</option><option value="REALIZADA">Realizada</option></select></label>}</article> }
function MyTasks() { const tasks = useData('/tareas'); const [message, setMessage] = useState(''); const updateStage = async (taskId, stageId, realizada) => { try { await request(`/tareas/${taskId}/etapas/${stageId}`, { method: 'PATCH', body: JSON.stringify({ realizada }) }, tasks.token); tasks.load(); setMessage('Etapa actualizada.') } catch (err) { setMessage(err.message) } }; const updateStatus = async (taskId, estado) => { try { await request(`/tareas/${taskId}/estado`, { method: 'PATCH', body: JSON.stringify({ estado }) }, tasks.token); tasks.load(); setMessage('Estado actualizado.') } catch (err) { setMessage(err.message) } }
  return <Shell title="Mis tareas"><section className="page-heading"><div><p className="eyebrow">Empleado</p><h1>Mis tareas asignadas</h1><p className="muted">Completá cada etapa y mantené actualizado el estado de tu trabajo.</p></div></section>{message && <p className="notice">{message}</p>}{tasks.loading ? <p>Cargando tareas...</p> : tasks.error ? <p className="form-error">{tasks.error}</p> : <TaskList tasks={tasks.data} employee onStage={updateStage} onStatus={updateStatus} />}</Shell>
}
function Progress({ value }) { return <div className="progress"><i style={{ width: `${value}%` }} /></div> }
createRoot(document.getElementById('root')).render(<App />)
